//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentenceAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://en.wikipedia.org/wiki/Affirmative_and_negative")]
        public string AffirmativeUrl {
            get {
                return ((string)(this["AffirmativeUrl"]));
            }
            set {
                this["AffirmativeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://en.wikipedia.org/wiki/Affirmative_and_negative")]
        public string NegativeUrl {
            get {
                return ((string)(this["NegativeUrl"]));
            }
            set {
                this["NegativeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://en.wikipedia.org/wiki/Interrogative")]
        public string InterrogativeUrl {
            get {
                return ((string)(this["InterrogativeUrl"]));
            }
            set {
                this["InterrogativeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/simplepresent.html")]
        public string SimplePresentUrl {
            get {
                return ((string)(this["SimplePresentUrl"]));
            }
            set {
                this["SimplePresentUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/presentcontinuous.html")]
        public string PresentContinuousUrl {
            get {
                return ((string)(this["PresentContinuousUrl"]));
            }
            set {
                this["PresentContinuousUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/presentperfect.html")]
        public string PresentPerfectUrl {
            get {
                return ((string)(this["PresentPerfectUrl"]));
            }
            set {
                this["PresentPerfectUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/presentperfectcontinuous.html")]
        public string PresentPerfectContinuousUrl {
            get {
                return ((string)(this["PresentPerfectContinuousUrl"]));
            }
            set {
                this["PresentPerfectContinuousUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/simplepast.html")]
        public string SimplePastUrl {
            get {
                return ((string)(this["SimplePastUrl"]));
            }
            set {
                this["SimplePastUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/pastcontinuous.html")]
        public string PastContinuousUrl {
            get {
                return ((string)(this["PastContinuousUrl"]));
            }
            set {
                this["PastContinuousUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/pastperfect.html")]
        public string PastPerfectUrl {
            get {
                return ((string)(this["PastPerfectUrl"]));
            }
            set {
                this["PastPerfectUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/pastperfectcontinuous.html")]
        public string PastPerfectContinuousUrl {
            get {
                return ((string)(this["PastPerfectContinuousUrl"]));
            }
            set {
                this["PastPerfectContinuousUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/simplefuture.html")]
        public string SimpleFutureUrl {
            get {
                return ((string)(this["SimpleFutureUrl"]));
            }
            set {
                this["SimpleFutureUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/futurecontinuous.html")]
        public string FutureContinuousUrl {
            get {
                return ((string)(this["FutureContinuousUrl"]));
            }
            set {
                this["FutureContinuousUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/futureperfect.html")]
        public string FuturePerfectUrl {
            get {
                return ((string)(this["FuturePerfectUrl"]));
            }
            set {
                this["FuturePerfectUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.englishpage.com/verbpage/futureperfectcontinuous.html")]
        public string FuturePerfectContinuousUrl {
            get {
                return ((string)(this["FuturePerfectContinuousUrl"]));
            }
            set {
                this["FuturePerfectContinuousUrl"] = value;
            }
        }
    }
}
